### ISSUE TITLE
Wireframe Layouts - Tracker Pages

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#11]
**Objective:** Wireframe all layouts for tracker related pages. 

**Scope:**
- [ ] Tracker landing page
- [ ] State level tracker pages
- [ ] County level tracker pages

**Acceptance Criteria:**
- [ ] All tracker related pages wireframed out
- [ ] Applicable pages visible on dev site
