### ISSUE TITLE
[Style & CMS] Debt Collector's Series

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#30]
**Objective:** To apply client approved styling to the Debt Collector's Series page, add CMS fields as needed for content on the page

**Tasks:**
- [x] Apply styles and content based on mockups, mobile -> desktop (need client approval of mockup)
- [ ] *BLOCKED* Add CMS fields for content (potential future iteration) 
- [ ] Add viewer panel for close up on each piece of art
- [ ] Add photo credits and captions (Copy TBD from client)
