### ISSUE TITLE
[Mockups] Tracker Related Pages

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#4]
**Objective:** Generate mockups for all tracker related pages included in sitemap and wireframes

**Scope:** Mockups should include the following pages - 
- [ ] Tracker landing page
- [ ] State level tracker page
- [ ] County level tracker page

**Acceptance Criteria:**
- [ ] Desktop mockups complete
- [ ] Mobile mockups complete
- [ ] Team & Creative Director signoff
- [ ] Client Signoff
