### ISSUE TITLE
Debt Collection Tracker Data Update

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/debt-collection-lab#63]
The following files contain new source data for the debt collection tracker:

- [x] update `scripts/shape.js` to fetch and parse the [S3 source file for lawsuits](https://debtcases.s3.us-east-2.amazonaws.com/lawsuit_data.csv). (currently using local `./data/lawsuit_data.csv` file)

- [x] adjust lawsuit data parser to only count default judgments where `case_completed` has a value of 1

- [x] update `gatsby-node.js` to fetch and parse the [S3 source file for demographics](https://debtcases.s3.us-east-2.amazonaws.com/demographic_data.csv).  (currently using `./static/data/demographics`)

- [x] review the site after build to ensure pages are rendering correctly with new data

- [x] once new data is displaying properly, rebuild social images

from the README:
> State and county pages have dynamic social images that can be created at build time. To re-build these images, set the `BUILD_IMAGES` env var to `1` or run `npm run build:all`.

- [x] move to staging, have client review and approve2

- [ ] once approved, update `CHANGELOG.md` with version bump (minor) and outline changes

- [ ] merge to `production` to release

**Comment by Lane** [comment]
@hoshmn just took a closer look at the data set, a few notes:

- date formats have changed, you will want to update the parser in `shapeFullData` to use `"%Y-%m-%d"` instead of `"%m/%d/%Y"`
- looks like there are quite a few rows without dates or with invalid dates (e.g. `0002-02-20`).  you'll need to reach out to either the client or Jeff from January Advisors to determine how these should be handled
- currently assuming that all zip code level filings correspond to North Dakota because it is the only location we are using zip code level data for.  should verify with Jeff @ January Advisors that this is true, and if not determine a method for determining which of the zip code level filings correspond to North Dakota.
