### ISSUE TITLE
Add bios / images to CMS config

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/debt-collection-lab#76]
#74 has changed the frontmatter format of `about-us.mdx`, so the CMS config for this page (`/src/cms/pages/about.js`) needs to be updated so the new frontmatter can be updated.

# Tasks

- [ ] add CMS config  for `primaryTeam` frontmatter using the following [widgets](https://www.netlifycms.org/docs/widgets/):
  - `name`: string
  - `role`: string
  - `title`: string
  - `bio`: text
  - `headshot`: image
  - `headshot_thumbnail`: image
- [ ] add CMS config for `secondaryTeam` frontmatter using the following [widgets](https://www.netlifycms.org/docs/widgets/):
  - `name`: string
  - `role`: string
- [ ] test locally and confirm all fields can be modified via CMS
  - run `npx netlify-cms-proxy-server` in a separate terminal alongside `npm run start` to test locally (http://localhost:8000/admin)
