### ISSUE TITLE
Top Plaintiffs Foundation | Data Download

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/debt-collection-lab#90]
## Objective
DCL would like to provide greater access to plaintiff data for site visitors. To do so, we will implement data download functionality on both county and state pages for plaintiff data. Link will be available within the "Top Debt Collectors" section of county and state pages. 

## Tasks
  - [ ] output CSV of all plaintiffs
  - [ ] create a new plaintiffs gatsby source node (based on plaintiffs CSV)
  - [ ] update page GraphQL query to pull plaintiffs for the given location
  - [ ] generate CSV on the page w/ download button

**Comment by achlong** [comment]
@hoshmn please make names all capitalized
